/*
 * 项目名: 全球大联盟
 * 文件名: Functions.java
 *
 * 版权声明:
 *     本系统的所有内容，包括源码、页面设计，文字、图像以及其他任何信息，
 *     如未经特殊说明，其版权均属圆通速递所有。
 *
 *     Copyright (c) 2014 圆通速递
 *     版权所有
 */
package com.yto.globalunion.common.enums;

import java.util.HashMap;
import java.util.Map;

/**
 * @author penglan
 *
 */
public enum Functions {
    // ####Menu######
    WAYBILL_MANAGEMENT("WAYBILL_MANAGEMENT", "/wayBillManagement"), //
    ACCOUNT_MANAGEMENT("ACCOUNT_MANAGEMENT", "/accountManagement"), //
    GLOBALPRICE_MANAGEMENT("GLOBALPRICE_MANAGEMENT", "/globalPriceManagement"), // ,
    PRIVILEGE_MANAGEMENT("PRIVILEGE_MANAGEMENT", "/privilegeManagement"), //
    LOG_MANAGEMENT("LOG_MANAGEMENT", "/logManagement"), //
    BASEDATA("BASEDATA", "/basedata"), //
    CUSTOM_MANAGEMENT("CUSTOM_MANAGEMENT", "/customManagement"), // 关务管理

    // 基础数据
    CURRENCY_MANAGEMENT("CURRENCY_MANAGEMENT", "/basedata/currencyManagement"), //
    EXCHANGE_RATE_MANAGEMENT("EXCHANGE_RATE_MANAGEMENT", "/basedata/exchangeRateManagement"), //
    IM_AND_EX_PORT_MANAGEMENT("IM_AND_EX_PORT_MANAGEMENT", "/basedata/imAndExPortManagement"), //
    FLIGHT_PORT_MANAGEMENT("FLIGHT_PORT_MANAGEMENT", "/basedata/flightPortManagement"), //
    AIRPORT_MANAGEMENT("AIRPORT_MANAGEMENT", "/basedata/airportManagement"), //
    UP_AND_DOWN_STREAM_MANAGEMENT("UP_AND_DOWN_STREAM_MANAGEMENT", "/basedata/upAndDownStreamManagement"), //
    ADDRESS_MANAGEMENT("ADDRESS_MANAGEMENT", "/basedata/addressManagement"), //
    EXPRESS_STATUS_MANAGEMENT("EXPRESS_STATUS_MANAGEMENT", "/basedata/expressstatusManagement"), //
    LENGTH_CONVERT_MANAGEMENT("LENGTH_CONVERT_MANAGEMENT", "/basedata/lengthConvertManagement"), //
    WEIGHT_CONVERT_MANAGEMENT("WEIGHT_CONVERT_MANAGEMENT", "/basedata/weightConvertManagement"), //
    FEES_MANAGEMENT("FEES_MANAGEMENT", "/basedata/feesManagement"), //
    BLC_MANAGEMENT("BLC_MANAGEMENT", "/basedata/customclearanceCompanyManagement"), //
    PRODUCT_MANAGEMENT("PRODUCT_MANAGEMENT", "/basedata/productManagement"), //
//    DEST_POINT_MANAGEMENT("DEST_POINT_MANAGEMENT", "/basedata/destPointManagement"), //
    // ####Menu######

    // 运单管理
    ORDER_MANAGEMENT("ORDER_MANAGEMENT", "/wayBillManagement/orderManagement"), //
    ORDER_TRANSLATION("ORDER_TRANSLATION", "/wayBillManagement/orderTranslation"), //
    YTO_ELECTRONIC_PROOF_PRINT("YTO_ELECTRONIC_PROOF_PRINT", "/wayBillManagement/ytoElectronicProofPrint"), //
    ORDER_REPORT_EXPORT("ORDER_REPORT_EXPORT", "/wayBillManagement/orderReportExport"), //
    MONITOR_SHIPMENTS("MONITOR_SHIPMENTS", "/wayBillManagement/monitorShipments"), //
    ORDER_ISSUE("ORDER_ISSUE", "/wayBillManagement/orderIssue"), //
    ORDER_INFO_IMPORT("ORDER_INFO_IMPORT", "/wayBillManagement/orderInfoImport"), //
    ORDER_INFO_ENTRY("ORDER_INFO_ENTRY", "/wayBillManagement/orderInfoEntry"), //
    DHL_TAXES_IMPORT("DHL_TAXES_IMPORT", "/wayBillManagement/dhlTaxesImport"), // DHL税费导入
    DHL_PRINT("DHL_PRINT", "/wayBillManagement/dhlPrint"), // DHL面单打印
    XN_IMPORT("XN_IMPORT", "/wayBillManagement/xnImport"), // 西浓订单导入
    XN_EXPORT("XN_EXPORT", "/wayBillManagement/xnExport"), // 西浓订单导出
    CLEARANCE_LOGISTICS_INFO_MANAGEMENT("CLEARANCE_LOGISTICS_INFO_MANAGEMENT","/wayBillManagement/clearanceLogistics"), //清关运单信息管理
    TMALL_ORDER_MANAGEMENT("TMALL_ORDER_MANAGEMENT","/wayBillManagement/tmallOrder"), //天猫国际订单相关模块
    EMS_TRANSPORT("EMS_TRANSPORT","/wayBillManagement/emsTransport"),//EMS航班信息管理
    EMS_FORECAST_EXPORT("EMS_FORECAST_EXPORT","/wayBillManagement/emsForecastExport"),//EMS 预报导出
    EMS_PRINT("EMS_PRINT","/wayBillManagement/emsPrint"),//EMS 面单打印
    GENERAL_GUN_SCAN_PRINT("GENERAL_GUN_SCAN_PRINT","/wayBillManagement/generalGunScanPrint"),//通用把枪扫描打印
    
    // 账单管理
    PAY_OR_INCOME_MANAGEMENT("PAY_OR_INCOME_MANAGEMENT", "/accountManagement/payOrCollectionManagement"), //
    BILL_ADJUSTMENT_MANAGEMENT("BILL_ADJUSTMENT_MANAGEMENT", "/accountManagement/billAdjustmentManagement"), //
    RECONCILIATION_NOTIFICATION("RECONCILIATION_NOTIFICATION", "/accountManagement/reconciliationNotification"), //

    // 国际价格管理
    REGIONAL_CLEARING_FEE_MANAGEMENT("REGIONAL_CLEARING_FEE_MANAGEMENT", "/globalPriceManagement/regionManagement"), //
    GLOBAL_PRICE_MANAGEMENT_REGION_MANAGEMENT("GLOBAL_PRICE_MANAGEMENT_REGION_MANAGEMENT", "/globalPriceManagement/regionalClearingFeeManagement"), //

    // 权限管理
    USER_MANAGEMENT("USER_MANAGEMENT", "/privilegeManagement/userManagement"), //
    ROLE_MANAGEMENT("ROLE_MANAGEMENT", "/privilegeManagement/roleManagement"), //
    SAFETY_MANAGEMENT("SAFETY_MANAGEMENT", "/privilegeManagement/safetyManagement"), //
    // 日志管理
    LOGIN_LOG_MANAGEMENT("LOGIN_LOG_MANAGEMENT", "/logManagement/loginLogManagement"), //
    OPERATION_LOG_MANAGEMENT("OPERATION_LOG_MANAGEMENT", "/logManagement/operationLogManagement"), //

    // 关务模块
    CLEARANCE_INFO_UPDATE("CLEARANCE_INFO_UPDATE", "/customManagement/clearanceInfoUpdate"), //
    CLEARANCE_INFO_MANAGEMENT("CLEARANCE_INFO_MANAGEMENT", "/customManagement/clearanceInfoManagement"), //
    // ####################menu end ####################

    // ####DestPointController######
//    DEST_POINT_MANAGEMENT_DELETE("DEST_POINT_MANAGEMENT_DELETE"), //
//    DEST_POINT_MANAGEMENT_SEARCH("DEST_POINT_MANAGEMENT_SEARCH"), //
//    DEST_POINT_MANAGEMENT_IMPORT_EXCEL("DEST_POINT_MANAGEMENT_IMPORT_EXCEL"), //

    // ####AddressController######
    ADDRESS_MANAGEMENT_ADD("ADDRESS_MANAGEMENT_ADD"), //
    ADDRESS_MANAGEMENT_DELETE("ADDRESS_MANAGEMENT_DELETE"), //
    ADDRESS_MANAGEMENT_UPDATE("ADDRESS_MANAGEMENT_UPDATE"), //
    ADDRESS_MANAGEMENT_SEARCH("ADDRESS_MANAGEMENT_SEARCH"), //
    ADDRESS_MANAGEMENT_IMPORT_EXCEL("ADDRESS_MANAGEMENT_IMPORT_EXCEL"),

    // ####AirportController######
    AIRPORT_MANAGEMENT_ADD("AIRPORT_MANAGEMENT_ADD"), //
    AIRPORT_MANAGEMENT_DELETE("AIRPORT_MANAGEMENT_DELETE"), //
    AIRPORT_MANAGEMENT_UPDATE("AIRPORT_MANAGEMENT_UPDATE"), //
    AIRPORT_MANAGEMENT_SEARCH("AIRPORT_MANAGEMENT_SEARCH"), //
    AIRPORT_MANAGEMENT_IMPORT_EXCEL("AIRPORT_MANAGEMENT_IMPORT_EXCEL"), //

    // ####BLCController######
    BLC_MANAGEMENT_ADD("BLC_MANAGEMENT_ADD"), //
    BLC_MANAGEMENT_DELETE("BLC_MANAGEMENT_DELETE"), //
    BLC_MANAGEMENT_UPDATE("BLC_MANAGEMENT_UPDATE"), //
    BLC_MANAGEMENT_SEARCH("BLC_MANAGEMENT_SEARCH"), //

    // ####ProductController######
    PRODUCT_MANAGEMENT_ADD("PRODUCT_MANAGEMENT_ADD"), //
    PRODUCT_MANAGEMENT_DELETE("PRODUCT_MANAGEMENT_DELETE"), //
    PRODUCT_MANAGEMENT_UPDATE("PRODUCT_MANAGEMENT_UPDATE"), //
    PRODUCT_MANAGEMENT_SEARCH("PRODUCT_MANAGEMENT_SEARCH"), //

    // ####CompanyController######
    UP_AND_DOWN_STREAM_MANAGEMENT_ADD("UP_AND_DOWN_STREAM_MANAGEMENT_ADD"), //
    UP_AND_DOWN_STREAM_MANAGEMENT_DELETE("UP_AND_DOWN_STREAM_MANAGEMENT_DELETE"), //
    UP_AND_DOWN_STREAM_MANAGEMENT_UPDATE("UP_AND_DOWN_STREAM_MANAGEMENT_UPDATE"), //
    UP_AND_DOWN_STREAM_MANAGEMENT_SEARCH("UP_AND_DOWN_STREAM_MANAGEMENT_SEARCH"), //

    // ####CurrencyController######
    CURRENCY_MANAGEMENT_SEARCH("CURRENCY_MANAGEMENT_SEARCH"), //
    CURRENCY_MANAGEMENT_ADD("CURRENCY_MANAGEMENT_ADD"), //
    CURRENCY_MANAGEMENT_UPDATE("CURRENCY_MANAGEMENT_UPDATE"), //
    CURRENCY_MANAGEMENT_DELETE("CURRENCY_MANAGEMENT_DELETE"), //

    // ####ExpressStatusController######
    EXPRESS_STATUS_MANAGEMENT_ADD("EXPRESS_STATUS_MANAGEMENT_ADD"), //
    EXPRESS_STATUS_MANAGEMENT_DELETE("EXPRESS_STATUS_MANAGEMENT_DELETE"), //
    EXPRESS_STATUS_MANAGEMENT_UPDATE("EXPRESS_STATUS_MANAGEMENT_UPDATE"), //
    EXPRESS_STATUS_MANAGEMENT_SEARCH("EXPRESS_STATUS_MANAGEMENT_SEARCH"), //

    // ####FeesController######
    FEES_MANAGEMENT_ADD("FEES_MANAGEMENT_ADD"), //
    FEES_MANAGEMENT_DELETE("FEES_MANAGEMENT_DELETE"), //
    FEES_MANAGEMENT_UPDATE("FEES_MANAGEMENT_UPDATE"), //
    FEES_MANAGEMENT_SEARCH("FEES_MANAGEMENT_SEARCH"), //

    // ####FlightController######
    FLIGHT_PORT_MANAGEMENT_ADD("FLIGHT_PORT_MANAGEMENT_ADD"), //
    FLIGHT_PORT_MANAGEMENT_DELETE("FLIGHT_PORT_MANAGEMENT_DELETE"), //
    FLIGHT_PORT_MANAGEMENT_UPDATE("FLIGHT_PORT_MANAGEMENT_UPDATE"), //
    FLIGHT_PORT_MANAGEMENT_SEARCH("FLIGHT_PORT_MANAGEMENT_SEARCH"), //
    FLIGHT_PORT_MANAGEMENT_IMPORT_EXCEL("FLIGHT_PORT_MANAGEMENT_IMPORT_EXCEL"),

    // ####LengthConversionController######
    LENGTH_CONVERT_MANAGEMENT_ADD("LENGTH_CONVERT_MANAGEMENT_ADD"), //
    LENGTH_CONVERT_MANAGEMENT_DELETE("LENGTH_CONVERT_MANAGEMENT_DELETE"), //
    LENGTH_CONVERT_MANAGEMENT_UPDATE("LENGTH_CONVERT_MANAGEMENT_UPDATE"), //
    LENGTH_CONVERT_MANAGEMENT_SEARCH("LENGTH_CONVERT_MANAGEMENT_SEARCH"), //

    // ####PortController######
    IM_AND_EX_PORT_MANAGEMENT_ADD("IM_AND_EX_PORT_MANAGEMENT_ADD"), //
    IM_AND_EX_PORT_MANAGEMENT_DELETE("IM_AND_EX_PORT_MANAGEMENT_DELETE"), //
    IM_AND_EX_PORT_MANAGEMENT_UPDATE("IM_AND_EX_PORT_MANAGEMENT_UPDATE"), //
    IM_AND_EX_PORT_MANAGEMENT_SEARCH("IM_AND_EX_PORT_MANAGEMENT_SEARCH"), //
    IM_AND_EX_PORT_MANAGEMENT_IMPORT_EXCEL("IM_AND_EX_PORT_MANAGEMENT_IMPORT_EXCEL"),

    // ####RateController######
    EXCHANGE_RATE_MANAGEMENT_ADD("EXCHANGE_RATE_MANAGEMENT_ADD"), //
    EXCHANGE_RATE_MANAGEMENT_DELETE("EXCHANGE_RATE_MANAGEMENT_DELETE"), //
    EXCHANGE_RATE_MANAGEMENT_UPDATE("EXCHANGE_RATE_MANAGEMENT_UPDATE"), //
    EXCHANGE_RATE_MANAGEMENT_SEARCH("EXCHANGE_RATE_MANAGEMENT_SEARCH"), //

    // ####WeightConversionController######
    WEIGHT_CONVERT_MANAGEMENT_ADD("WEIGHT_CONVERT_MANAGEMENT_ADD"), //
    WEIGHT_CONVERT_MANAGEMENT_DELETE("WEIGHT_CONVERT_MANAGEMENT_DELETE"), //
    WEIGHT_CONVERT_MANAGEMENT_UPDATE("WEIGHT_CONVERT_MANAGEMENT_UPDATE"), //
    WEIGHT_CONVERT_MANAGEMENT_SEARCH("WEIGHT_CONVERT_MANAGEMENT_SEARCH"), //

    // ####BillAdjustmentController######
    BILL_ADJUSTMENT_MANAGEMENT_EXPORTXLS("BILL_ADJUSTMENT_MANAGEMENT_EXPORTXLS"), //
    BILL_ADJUSTMENT_MANAGEMENT_SEARCH("BILL_ADJUSTMENT_MANAGEMENT_SEARCH"), //
    BILL_ADJUSTMENT_MANAGEMENT_UPDATE("BILL_ADJUSTMENT_MANAGEMENT_UPDATE"), //

    // ####PayOrIncomeController######
    PAYORCOLLECTION_MANAGEMENT_SEARCH("PAYORCOLLECTION_MANAGEMENT_SEARCH"), PAYORCOLLECTION_MANAGEMENT_EXPORTORDER("PAYORCOLLECTION_MANAGEMENT_EXPORTORDER"), PAYORCOLLECTION_MANAGEMENT_SETTINGSBILL("PAYORCOLLECTION_MANAGEMENT_SETTINGSBILL"),

    // ####ReconciliationNotificationController######
    RECONCILIATION_NOTIFICATION_SEARCH("RECONCILIATION_NOTIFICATION_SEARCH"), //
    RECONCILIATION_NOTIFICATION_ADD("RECONCILIATION_NOTIFICATION_ADD"), //
    RECONCILIATION_NOTIFICATION_UPDATE("RECONCILIATION_NOTIFICATION_UPDATE"), //
    RECONCILIATION_NOTIFICATION_DELETE("RECONCILIATION_NOTIFICATION_DELETE"),
    // ####IndexController######
    _INDEX("_INDEX"), //

    // ####RegionClearingFeeController######
    REGIONAL_CLEARING_FEE_MANAGEMENT_ADD("REGIONAL_CLEARING_FEE_MANAGEMENT_ADD"), //
    REGIONAL_CLEARING_FEE_MANAGEMENT_DELETE("REGIONAL_CLEARING_FEE_MANAGEMENT_DELETE"), //
    REGIONAL_CLEARING_FEE_MANAGEMENT_UPDATE("REGIONAL_CLEARING_FEE_MANAGEMENT_UPDATE"), //
    REGIONAL_CLEARING_FEE_MANAGEMENT_SEARCH("REGIONAL_CLEARING_FEE_MANAGEMENT_SEARCH"), //

    // ####RegionController######
    GLOBAL_PRICE_MANAGEMENT_ADD("GLOBAL_PRICE_MANAGEMENT_ADD"), //
    GLOBAL_PRICE_MANAGEMENT_DELETE("GLOBAL_PRICE_MANAGEMENT_DELETE"), //
    GLOBAL_PRICE_MANAGEMENT_UPDATE("GLOBAL_PRICE_MANAGEMENT_UPDATE"), //
    GLOBAL_PRICE_MANAGEMENT_SEARCH("GLOBAL_PRICE_MANAGEMENT_SEARCH"), //
    GLOBAL_PRICE_MANAGEMENT_IMPORT_EXCEL("GLOBAL_PRICE_MANAGEMENT_IMPORT_EXCEL"), //

    // ####MonitorShipmentsController######
    MONITOR_SHIPMENTS_SEARCH("MONITOR_SHIPMENTS_SEARCH"), //
    /*
     * 运单管理
     */
    // ####OrderController######
    ORDER_MANAGEMENT_QUERY("ORDER_MANAGEMENT_QUERY"), //
    ORDER_MANAGEMENT_SEARCH("ORDER_MANAGEMENT_SEARCH"), //
    ORDER_MANAGEMENT_EXPORT("ORDER_MANAGEMENT_EXPORT"), //
    ORDER_MANAGEMENT_VIEW_DETAILS("ORDER_MANAGEMENT_VIEW_DETAILS"), //

    // ####OrderEntryController######
    ORDER_ENTRY_SCANNING_GUN("ORDER_ENTRY_SCANNING_GUN"), //
    ORDER_ENTRY_SCANNING_GUN_EXCEL_EXPORT("ORDER_ENTRY_SCANNING_GUN_EXCEL_EXPORT"), //

    // ####OrderEntryAndImportController######
    ORDER_INFO_IMPORT_IMPORT_EXCEL("ORDER_INFO_IMPORT_IMPORT_EXCEL"), //
    ORDER_INFO_IMPORT_SEARCH("ORDER_INFO_IMPORT_SEARCH"),//
    ORDER_INFO_IMPORT_UPDATE("ORDER_INFO_IMPORT_UPDATE"),//
    ORDER_INFO_IMPORT_DELETE("ORDER_INFO_IMPORT_DELETE"),//

    // ####XNImportController######
    XN_DAT_IMPORT("XN_DAT_IMPORT"),

    // ####XNExportController######
    XN_EXCEL_EXPORT("XN_EXCEL_EXPORT"), XN_EXPORT_SEARCH("XN_EXPORT_SEARCH"), // 西浓导出和查询
    
    //####ClearanceLogisticsController######
    CLI_IMPORT("CLI_IMPORT"),CLI_SEARCH("CLI_SEARCH"),//清关运单导入和查询

    // ####DhlTaxesImportController######
    DHL_TAXES_IMPORT_IMPORT_EXCEL("DHL_TAXES_IMPORT_IMPORT_EXCEL"), //

    // ####OrderTranslateController######
    ORDER_TRANSALTE_SEARCH("ORDER_TRANSALTE_SEARCH"), // 运单翻译查询
    ORDER_TRANSALTE_MARKTASK("ORDER_TRANSALTE_MARKTASK"), // 运单翻译标记任务

    // ####OrderIssueController######

    // ####OrderReportExportController######
    ORDER_REPORT_EXPORT_SEARCH("ORDER_REPORT_EXPORT_SEARCH"), //
    ORDER_REPORT_EXPORT_EXPORT("ORDER_REPORT_EXPORT_EXPORT"),
    // ####OrderTranslateController######
    ORDER_TRANSLATION_QUERY("ORDER_TRANSLATION_QUERY"), //
    ORDER_TRANSLATION_ORDER_DETAIL("ORDER_TRANSLATION_ORDER_DETAIL"), //
    ORDER_TRANSLATION_ORDER_MARK_TASKS("ORDER_TRANSLATION_ORDER_MARK_TASKS"), //

    // ####WayBillPrintController######
    YTO_ELECTRONIC_PROOF_PRINT_VIEW_PRINT_DETAIL("YTO_ELECTRONIC_PROOF_PRINT_VIEW_PRINT_DETAIL"), //

    // ####WayBillPrintController######

    // ####YtoElectronicProofPrintController######
    ELECTRONIC_PROOF_PRINT_SEARCH("ELECTRONIC_PROOF_PRINT_SEARCH"), // 查询
    ELECTRONIC_PROOF_PRINT("ELECTRONIC_PROOF_PRINT"), // 打印

    LOGIN_LOG_MANAGEMENT_SEARCH("LOGIN_LOG_MANAGEMENT_SEARCH"), //
    OPERATE_LOG_MANAGEMENT_SEARCH("OPERATE_LOG_MANAGEMENT_SEARCH"), //
    // ####EmsForecastExport######
    EMS_FORECAST_EXPORT_SEARCH("EMS_FORECAST_EXPORT_SEARCH"),
    EMS_FORECAST_EXCEL_EXPORT("EMS_FORECAST_EXCEL_EXPORT"),
    // ####EmsForecastExport######
    
    // ####UserManagementController######
    USER_MANAGEMENT_ADD("USER_MANAGEMENT_ADD"), //
    USER_MANAGEMENT_DELETE("USER_MANAGEMENT_DELETE"), //
    USER_MANAGEMENT_UPDATE("USER_MANAGEMENT_UPDATE"), //
    USER_MANAGEMENT_SEARCH("USER_MANAGEMENT_SEARCH"), //

    // ####RoleManagementController######
    ROLE_MANAGEMENT_ADD("ROLE_MANAGEMENT_ADD"), //
    ROLE_MANAGEMENT_DELETE("ROLE_MANAGEMENT_DELETE"), //
    ROLE_MANAGEMENT_UPDATE("ROLE_MANAGEMENT_UPDATE"), //
    ROLE_MANAGEMENT_SEARCH("ROLE_MANAGEMENT_SEARCH"), //
    // ####SafetyManagementController######
    SAFETY_MANAGEMENT_ASSIGN("SAFETY_MANAGEMENT_ASSIGN"),
    // ######ClearanceInfoUpdate####
    CLEARANCE_INFO_UPDATE_SEARCH("CLEARANCE_INFO_UPDATE_SEARCH"), //
    CLEARANCE_INFO_UPDATE_VIEWDETAILS("CLEARANCE_INFO_UPDATE_VIEWDETAILS"), //
    CLEARANCE_INFO_UPDATE_IMPORT("CLEARANCE_INFO_UPDATE_IMPORT"), //
    CLEARANCE_INFO_UPDATE_EXPORT("CLEARANCE_INFO_UPDATE_EXPORT"), //
    //#######Tmall Order #########
//    TMALL_ORDER("TMALL_ORDER"),
//    TMALL_ORDER_LIST("TMALL_ORDER_LIST"),
//    TMALL_ORDER_LOGISTICS("TMALL_ORDER_LOGISTICS"),
//    TMALL_ORDER_DETAIL("TMALL_ORDER_DETAIL"),
    // ####Default######
    
    DEFAULT("DEFAULT");

    private static final Map<String, Functions> CODE_TO_FUNCTION_MAP = new HashMap<>();
    private static final Map<String, String>    CODE_TO_URL_MAP      = new HashMap<>();
    private String                              code;
    private String                              url;

    static {
        for (Functions f : Functions.values()) {
            CODE_TO_FUNCTION_MAP.put(f.code, f);
            CODE_TO_URL_MAP.put(f.code, f.url);
        }
    }

    private Functions(String code) {
        this.code = code;
    }

    private Functions(String code, String url) {
        this.code = code;
        this.url = url;
    }

    public static Functions getFunctions(String code) {
        return CODE_TO_FUNCTION_MAP.containsKey(code) ? CODE_TO_FUNCTION_MAP.get(code) : DEFAULT;
    }

    public static String getUrlByFunctionCode(String code) {
        return CODE_TO_URL_MAP.containsKey(code) ? CODE_TO_URL_MAP.get(code) : "#";
    }

    /**
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * @return the url
     */
    public String getUrl() {
        return url;
    }
}
